#!/usr/bin/env bash

set -euxo pipefail

git pull

if [ -f "stop" ]; then
  echo "stop"
  exit 0
fi


yarn data --force

function has_changed() {
  local filepath=$1
  if ! diff -q <(git show HEAD:$filepath | jq 'del(.updatedAt)') <(jq 'del(.updatedAt)' $filepath) &>/dev/null; then
    true
  else
    false
  fi
}

if has_changed "public/data/sign.json"; then
  git add "public/data/sign.json"
  git commit -m "update signatures data"
  git push
else
  echo 'unchanged'
fi


if has_changed "public/data/addresses.json"; then
  git add "public/data/addresses.json"
  git commit -m "update addresses data"
  git push
else
  echo 'unchanged'
fi
