export const N_PER_REGION_MAX = 2_500;
export const TOTAL_REQUIRED = 100_000;
export const N_REGIONS_REQUIRED = TOTAL_REQUIRED / N_PER_REGION_MAX;

export const TOTAL_DESIRED = 150_000;
export const N_PER_REGION_DESIRED = TOTAL_DESIRED / N_REGIONS_REQUIRED;
